# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Linette Lim"                                # Your name
  image: img/2212_Lim_L_011.png
  
  # start of the navigation bar at the top of the website
  navbar:
    
    # your sub-pages
    left:
      - text: "About"
        href: about/index.qmd
      - text: "Research"
        href: research/index.qmd
      - text: "Teaching"
        href: teaching/index.qmd
      - text: "CV"
        href: cv/index.qmd
      - text: "Contact"
        href: contact/index.qmd
  

# Don't touch unless you know what you are doing :) ------------
  search: false
  #  location: navbar
  #  type: textbox
  page-footer: 
    left: |
      <span class="faux-block">Website template &#169; 2023 Marvin Schmitt CC BY-SA 4.0</span>
    right: |
      <span class="faux-block"><a href="https://github.com/marvinschmitt/quarto-website-template/">View source on GitHub</a></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    header-includes:
      <style>@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:ital,wght@0,100..700;1,100..700&family=IBM+Plex+Serif:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&display=swap');</style>