---
layout: page
title: Research
excerpt: Research
execute:
  freeze: false  # never re-render during project render
engine: knitr 
resources:
  - "mas.pdf"
  - "socalled.pdf"
research:
  mas: "mas.pdf"
  socalled: "socalled.pdf"
  manuscript: "manuscript.pdf"
  appendix: "appendix.pdf"
---

```{=html}
<div class="text-align: left;">

<hr style="margin: 2em 0;">
<h3 style="margin-bottom: 1.5em;"><em>Publications</em></h3>
<ul>
      <li>
      <a href="https://doi.org/10.1080/13569775.2025.2586182" target="_blank"><strong>Friends and Enemies: External Threats and the Delegitimization of Foreign Media in China.</strong></a> 2025.
      <i>Contemporary Politics.</i>
      &ensp;<a href="`r rmarkdown::metadata$research$manuscript`" target="_blank">
       [Manuscript]
      </a>
      &ensp;<a href="`r rmarkdown::metadata$research$appendix`" target="_blank">
       [Appendix]
      </a>
      <ul>
        <li><a href="https://bsky.app/profile/psaautocracy.bsky.social/post/3lv4f5ixbpc2z" target="_blank">
            Best PhD Paper 2025
          </a>, Autocracy &amp; Regime Change Specialist Group,<br>
          <a href="https://www.psa.ac.uk/" target="_blank">Political Studies Association</a></li>
      </ul>
    </li>
    
    <li>
       <a href="https://doi.org/10.1177/19401612251379585" target="_blank"><strong>Foreign Correspondence in China: Authoritarian Media Control and Journalistic Responses.</strong></a> 2025.
      <i>The Internationational Journal of Press/Politics.</i>
    </li>
    
    <li>
    <a href="https://doi.org/10.1017/jea.2025.7" target="_blank"><strong>The Use of ‘So-Called’ as a Propaganda Device in China.</strong></a> 2025.
    <i>The Journal of East Asian Studies.</i> (with <a href="https://alexdukalskis.wordpress.com/" target="_blank">Alexander Dukalskis</a>).
  </li>
</ul>

<hr style="margin: 2em 0;">
<h3 style="margin-bottom: 1.5em;"><em>Under Review</em></h3>
  <ul>
    <li>
      <strong>Party and Personalism in China’s Autocratic Legitimation.</strong>
      <i>(with <a href="https://alexdukalskis.wordpress.com/" target="_blank">Alexander Dukalskis</a>).<br>
      Book Chapter Under Review.</i>
    </li>
  </ul>
  
<hr style="margin: 2em 0;">
<h3 style="margin-bottom: 1.5em;"><em>Working Papers</em></h3>
  <ul>
    <li>
      <strong>Who Believes and Who Shares Fake News: A Multi-Agent System Application for Experimental Misinformation Research with LLMs.</strong>
      <i>(with <a href="https://davidycliao.github.io/" target="_blank">Yen-Chieh Liao</a> and <a href="https://sjankin.com/" target="_blank">Slava Jankin</a>).</i>
       &ensp;<a href="`r rmarkdown::metadata$research$mas`" target="_blank">
       [Pre-analysis Plan]
      </a>
    </li>
    
    <li>
      <strong>How do Propaganda Frames Shift Behavioural Intentions towards International Journalists? Evidence from China.</strong>
    </li>
  </ul>

</div>