---
layout: page
title: Teaching
excerpt: Teaching
execute:
  freeze: false  # never re-render during project render
engine: knitr 
resources:
  - "media politics_syllabus.pdf"
teaching:
  syllabus: "media politics_syllabus.pdf"
---

```{=html}
<div style="text-align: left;">

<p>During my doctoral training – which is structured to prioritize research – I actively sought pedagogical training and classroom experience. I have guest lectured for <a href="https://alexdukalskis.wordpress.com/" target="_blank">Alexander Dukalskis</a>' Introduction to Asian Politics (POL30690) and <a href="https://www.nikitakhokhlov.com/" target="_blank">Nikita Khokhlov</a>'s Political Communication and Propaganda (POL36220) modules. I was also one of a small handful of PhD candidates approved to design and teach my own module. This module, Media Politics under Authoritarianism (POL36250), was taught to advanced undergraduate students in Autumn 2025 at University College Dublin. The module received highly positive evaluations (4.7/ 5.0), with students noting clarity and engagement.

<hr style="margin: 2em 0;">
<h3 style="margin-bottom: 1.5em;"><em>Course Description</em></h3>

  <p>
    <strong><a href="`r rmarkdown::metadata$teaching$syllabus`" target="_blank">Media Politics under Authoritarianism</a></strong><br></p>
  <p>The study of media and power is dominated by research on developed democracies, where the press operates fairly freely. However, this is where only a third of the world’s population lives, according to the V-Dem (Varieties of Democracy) Institute. Given that 70 percent of humanity reside in authoritarian states, there is an urgent need to rethink our understanding of media politics. This module introduces students to interdisciplinary research on media in non-Western and non-liberal contexts. Students will read and critically discuss contemporary scholarship, analyzing specific cases of media control and societal responses to such control.
  </p>


<hr style="margin: 2em 0;">
<h3 style="margin-bottom: 1.5em;"><em>Student Evaluations</em></h3>
  
 <blockquote style="margin: 0 0 1.5em 0;">"Very informative and interesting topic presented in an extremely organised way. The lecturer always engaged with the class and the interactive element helped concepts to become clearer."</blockquote>

 <blockquote style="margin: 0 0 1.5em 0;">"Friendly, helpful, good and detailed slides, not overburdened with readings so was able to gather more in depth understanding and material felt manageable."</blockquote>

 <blockquote style="margin: 0 0 1.5em 0;">"Really enjoyed the module. Linette was so approachable for any issues outside of class and the content and assessments were clear and structured with no ambiguity. Thank you!"</blockquote>

 <blockquote style="margin: 0 0 1.5em 0;">"As a foreign student, I really appreciated this module because the teacher brings about her own professional experience and we can feel what she learnt during her career. It was perfect to study the cases."</blockquote>

 <blockquote style="margin: 0 0 1.5em 0;">"I loved taking this module because the subject interested me and the teacher’s ability to share her personal experience regarding autocracies was very helpful as well."</blockquote>

 <blockquote style="margin: 0 0 1.5em 0;">"Very interesting with a lot of examples from different parts of the world and readings. Also it was good to go over the readings in class to review them after reading and having the professor explain."</blockquote>

 <blockquote style="margin: 0 0 1.5em 0;">"Very enjoyable. Content is easy to follow along, not overly complicated like other politics modules I have taken."</blockquote>

 <blockquote style="margin: 0 0 1.5em 0;">"Really well structured, interactive and enjoyable module."</blockquote>
</div>